#ifndef CYGONCE_PKGCONF_HAL_ARM_BP2016_H
#define CYGONCE_PKGCONF_HAL_ARM_BP2016_H
/*
 * File <pkgconf/hal_arm_bp2016.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_KERNEL_TREAHD_STATS 32
#define CYGNUM_KERNEL_TREAHD_STATS_32
#define CYGHWR_HAL_ARM_FPU 1
#define CYGHWR_HAL_ARM_FPU_D32 1
#define CYGHWR_HAL_ARM_NEON 1
#define CYGHWR_HAL_ARM_BP2016 BP2016UL
#define CYGHWR_HAL_ARM_BP2016_BP2016UL
#define CYGINT_HAL_INTERRUPT_TIME_STAT 1
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 950000
#define CYGNUM_HAL_RTC_PERIOD_950000
#define CYGNUM_HAL_STARTUP_STACK_SIZE 2048
#define CYGNUM_HAL_STARTUP_STACK_SIZE_2048
#define CYGDBG_RELEASE_MSG 1
#define CYGDBG_RELEASE_MSG_1
#define CYGDBG_RELEASE_VERSION 170
#define CYGDBG_RELEASE_VERSION_170
#define CYGDBG_RELEASE_TYPE 0
#define CYGDBG_RELEASE_TYPE_0
#define CYGHWR_HAL_ASIC_CLK 1

#endif
