#ifndef CYGONCE_PKGCONF_HAL_ARM_BP2016_ASIC_H
#define CYGONCE_PKGCONF_HAL_ARM_BP2016_ASIC_H
/*
 * File <pkgconf/hal_arm_bp2016_asic.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define HAL_PLATFORM_CPU    "Cortex-A7"
#define HAL_PLATFORM_BOARD  "BP2016 ASIC"
#define CYGNUM_HAL_RTC_TIMER_ID 0
#define CYGNUM_HAL_RTC_TIMER_ID_0
#define CYGNUM_HAL_KERNEL_COUNTERS_CLOCK_ISR_DEFAULT_PRIORITY 160
#define CYGNUM_HAL_KERNEL_COUNTERS_CLOCK_ISR_DEFAULT_PRIORITY_160
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 8
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_8
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_115200
#define CYGBLD_GLOBAL_OPTIONS 1

#endif
